### ISSUE TITLE
Standardize hymn title on own slide

### ISSUE THREAD

**Issue by stephenangelico** [AshyPC/OHP-HTML#2]
Changing mpnimport.pike means breaking compatibility with past Git history. Using a normal `<h3>` tag as before does not allow the greater size and vertical centering that the `<address>` tag has.
Maybe create a class using a specific selector in ohp.css? Something like this:
```css
.hymntitle > h3 {
	font-style: normal;
	font-size: 200%;
	position: absolute;
	top: 50%;
	width: calc(100% - 20px);
	margin: -1.4em 0 0 0;
	text-align: center;
	line-height: 150%;
}
```
(Attributes copied from `address` selector. Actual values are subject to change.)
Using a section class isn't that big of a problem, and would likely make the code cleaner.
